# Generated by Django 4.2.7 on 2023-11-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activation',
            name='code',
        ),
    ]
